definitions/CourseFull.yaml
definitions/CourseResult.yaml
definitions/CourseResultFull.yaml
definitions/PersonFull.yaml
paths/CourseResultCollection.yaml
paths/CourseResultInstance.yaml
paths/TestResultCollection.yaml
paths/TestResultInstance.yaml
spec.yaml

As discussed with @tomkuipers and @usapieter this morning.

Adapt course/test results for consistency (fixes #8)

---

definitions/Person.yaml
definitions/PersonFull.yaml
paths/PersonCollection.yaml
paths/PersonCourseCollection.yaml
paths/PersonCourseGroupCollection.yaml
paths/PersonEducationalPlanCollection.yaml
paths/PersonInstance.yaml
spec.yaml

* Fixed naming inconsistencies
* Reduced name fields
* Added surname prefix
* Limited sorting/filtering options
* Converted links

Processed all /persons to-dos

---

definitions/NewsFeed.yaml
definitions/NewsItem.yaml

Specify format URI for URLs in NewsFeed item

---

paths/CourseOfferingInstance.yaml

This pull request changes the courseOfferings path to kebab-case.

Change courseOfferings path to kebab-case

---

schemas/EducationalProgramme.yaml

Fix a typo in the description of the the fieldsOfStudy field

Fix non-breaking typo in description of fieldsOfStudy

---

paths/CourseCollection.yaml
schemas/EducationalProgramme.yaml

Fixes the courseCollection request by adding a missing query parameter and correcting a typo in the educationalProgramme schema.

Fix course collection

---

v4/schemas/Association.yaml
v4/schemas/Component.yaml
v4/schemas/Course.yaml
v4/schemas/CourseOffering.yaml
v4/schemas/NewsItem.yaml
v4/schemas/Offering.yaml
v4/schemas/Program.yaml
v4/schemas/ProgramOffering.yaml
v4/schemas/Room.yaml

This PR resolves #90. It proposes new or updated values for most of the enumerations.

Updated most of the enums for v4

---

v4/paths/AcademicSessionCollection.yaml
v4/paths/AcademicSessionOfferingCollection.yaml
v4/paths/BuildingCollection.yaml
v4/paths/BuildingRoomCollection.yaml
v4/paths/ComponentOfferingCollection.yaml
v4/paths/CourseCollection.yaml
v4/paths/CourseComponentCollection.yaml
v4/paths/CourseOfferingCollection.yaml
v4/paths/NewsFeedCollection.yaml
v4/paths/NewsFeedItemCollection.yaml
v4/paths/OfferingAssociationCollection.yaml
v4/paths/OrganizationCollection.yaml
v4/paths/OrganizationComponentCollection.yaml
v4/paths/OrganizationCourseCollection.yaml
v4/paths/OrganizationOfferingCollection.yaml
v4/paths/OrganizationProgramCollection.yaml
v4/paths/PersonAssociationCollection.yaml
v4/paths/PersonCollection.yaml
v4/paths/ProgramCollection.yaml
v4/paths/ProgramCourseCollection.yaml
v4/paths/ProgramOfferingCollection.yaml
v4/paths/RoomCollection.yaml

added a lot of filters and sorting on the collection endpoints according to the table on the wiki: https://wiki.surfnet.nl/display/OwCat/Attributen
the enums need to be verified if they match with the enums of #95

added filters and sorting

---

v4/parameters/pageNumber.yaml
v4/parameters/personSearch.yaml
v4/paths/AssociationInstance.yaml
v4/paths/PersonCollection.yaml
v4/schemas/Address.yaml
v4/schemas/AssociationExpanded.yaml
v4/schemas/Offering.yaml
v4/spec.yaml

This PR bundles fixes for #105 #109  #112 #115 #116 and #117. All these issues are about small inconsistencies or unclear documentation.

Multiple fixes

---

v3/schemas/Institution.yaml

Replace with 
```yaml
type: string
format: uri
```

v3 Institution.yaml - url is not a JSON Schema type

---

v4/paths/OrganizationCourseCollection.yaml

Fix missing link

---

v4/schemas/AcademicSession.yaml
v4/schemas/Association.yaml
v4/schemas/Building.yaml
v4/schemas/Component.yaml
v4/schemas/Course.yaml
v4/schemas/NewsFeed.yaml
v4/schemas/NewsItem.yaml
v4/schemas/Offering.yaml
v4/schemas/Organization.yaml
v4/schemas/Person.yaml
v4/schemas/PersonMin.yaml
v4/schemas/Problem.yaml
v4/schemas/Program.yaml
v4/schemas/Result.yaml
v4/schemas/Room.yaml
v4/schemas/Service.yaml

updated the descriptions on the objects to make OOAPI objects more comparable to other specifications for issue #120

add descriptions to the OOAPI objects

---

v4/schemas/AcademicSession.yaml
v4/schemas/NewsItem.yaml
v4/schemas/NewsItemExpanded.yaml
v4/schemas/Person.yaml
v4/schemas/PersonMin.yaml
v4/schemas/Problem.yaml
v4/schemas/Result.yaml
v4/schemas/Room.yaml

Update for date format examples (from date time to date)
update number examples to string
Update relation in newsItem and newsFeed

Minor updates relationnames

---

v4/parameters/pageNumber.yaml

This PR fixes a typo and clarifies how we deal with pagination

Fix typo and clarify page numbers

---

v4/paths/AcademicSessionCollection.yaml
v4/paths/AcademicSessionOfferingCollection.yaml
v4/paths/BuildingCollection.yaml
v4/paths/BuildingRoomCollection.yaml
v4/paths/ComponentOfferingCollection.yaml
v4/paths/CourseCollection.yaml
v4/paths/CourseComponentCollection.yaml
v4/paths/CourseOfferingCollection.yaml
v4/paths/NewsFeedCollection.yaml
v4/paths/NewsFeedItemCollection.yaml
v4/paths/OfferingAssociationCollection.yaml
v4/paths/OrganizationCollection.yaml
v4/paths/OrganizationComponentCollection.yaml
v4/paths/OrganizationCourseCollection.yaml
v4/paths/OrganizationOfferingCollection.yaml
v4/paths/OrganizationProgramCollection.yaml
v4/paths/PersonAssociationCollection.yaml
v4/paths/PersonCollection.yaml
v4/paths/ProgramCollection.yaml
v4/paths/ProgramCourseCollection.yaml
v4/paths/ProgramOfferingCollection.yaml
v4/paths/RoomCollection.yaml

add ext object to collections

---

.github/ISSUE_TEMPLATE/CHANGE-REQUEST.yml

added a field to the issue template, to leave a question for the work group

update issue template with 'your-question'

---

CHANGELOG.md

Updates the changelog for #169

Update changelog for pagination

---

v5/enumerations/academicSessionType.yaml
v5/paths/AcademicSessionCollection.yaml
v5/paths/AcademicSessionInstance.yaml
v5/schemas/AcademicSession.yaml
v5/schemas/AcademicSessionExpanded.yaml

changes to academic sessions according to #161

add academicSessionType and children to academicSession

---

CHANGELOG.md
v5/schemas/Program.yaml
v5/spec.yaml

This PR fixes #156 by removing the attribute `profileOfProgram` from Program.

Remove `profileOfProgram` attribute from `Program`

---

CHANGELOG.md
v5/changed.md
v5/enumerations/groupType.yaml
v5/paths/GroupCollection.yaml
v5/paths/GroupInstance.yaml
v5/paths/GroupPersonCollection.yaml
v5/paths/OfferingGroupCollection.yaml
v5/paths/OrganizationGroupCollection.yaml
v5/paths/PersonGroupCollection.yaml
v5/schemas/Group.yaml
v5/schemas/GroupExpanded.yaml
v5/spec.yaml

all things related to groups are added according to #47

add group api

---

v5/enumerations/educationSpecificationType.yaml
v5/paths/EducationSpecificationCollection.yaml
v5/paths/ProgramOfferingCollection.yaml
v5/paths/Service.yaml
v5/schemas/Building.yaml
v5/schemas/Organization.yaml
v5/schemas/PersonProperties.yaml
v5/spec.yaml

This PR has some minor fixes to make sure the spec renders correctly in the documentation

Some minor fixes

---

v5-beta/schemas/Address.yaml

Fix addressType typo

---

v5-beta/docs.html

Updates redoc version to latest.

Update redoc version

---

docs/consumers/eduxchange.md
v5-beta/consumers/EDUXCHANGE/V1/Course.yaml
v5-beta/consumers/EDUXCHANGE/V1/Program.yaml

Adding documentation for the eduXchange consumer

---

v5-beta/enumerations/formalDocument.yaml
v5-beta/schemas/Course.yaml
v5-beta/schemas/CourseProperties.yaml
v5-beta/schemas/EducationSpecification.yaml
v5-beta/schemas/EducationSpecificationProperties.yaml
v5-beta/schemas/Program.yaml
v5-beta/schemas/ProgramProperties.yaml

Fixes repeating validFrom and validTo fields in timelineOverrides

Fix repeating validFrom and validTo fields in timelineOverrides

---

docs/consumers/eduxchange.md

Fix another typo in docs

---

docs/consumers/eduxchange.md

Fixes eduxchange documentation

Fixes eduxchange documentation

---

v5/schemas/AcademicSession.yaml

This PR fixes a missing primaryCode and otherCodes on AcademicSession.

Bugfix: missing primaryCode and otherCodes on AcademicSession

---

docs/consumers/rio.md

Values switched in consentParticipationSTEP

Fixed error in rio.md

---

v4/paths/AcademicSessionOfferingCollection.yaml
v4/paths/ComponentOfferingCollection.yaml
v4/paths/CourseOfferingCollection.yaml
v4/paths/OrganizationOfferingCollection.yaml
v4/paths/ProgramOfferingCollection.yaml
v4/schemas/Offering.yaml

This PR fixes an accidental search-and-replace in the v4 directory.

Fix accidental v4 isLineItem replacement

---

v5/parameters/consumer.yaml
v5/schemas/AcademicSession.yaml
v5/schemas/AssociationProperties.yaml
v5/schemas/Building.yaml
v5/schemas/Component.yaml
v5/schemas/Consumer.yaml
v5/schemas/CourseProperties.yaml
v5/schemas/EducationSpecificationProperties.yaml
v5/schemas/Group.yaml
v5/schemas/NewsFeed.yaml
v5/schemas/NewsItem.yaml
v5/schemas/OfferingProperties.yaml
v5/schemas/Organization.yaml
v5/schemas/PersonProperties.yaml
v5/schemas/ProgramProperties.yaml
v5/schemas/Room.yaml
v5/schemas/Service.yaml

This PR fixes a broken link in the technical documentation.

Fix broken link in the technical documentation

---

v6/enumerations/academicSessionType.yaml
v6/enumerations/associationRole.yaml
v6/enumerations/codeType.yaml
v6/enumerations/costType.yaml
v6/enumerations/educationSpecificationType.yaml
v6/enumerations/formalDocument.yaml
v6/enumerations/gender.yaml
v6/enumerations/groupType.yaml
v6/enumerations/learningComponentType.yaml
v6/enumerations/level.yaml
v6/enumerations/levelOfQualification.yaml
v6/enumerations/modeOfStudy.yaml
v6/enumerations/modesOfDelivery.yaml
v6/enumerations/newsItemType.yaml
v6/enumerations/offeringType.yaml
v6/enumerations/qualificationAwarded.yaml
v6/enumerations/resultState.yaml
v6/enumerations/resultValueType.yaml
v6/enumerations/roomType.yaml
v6/enumerations/sector.yaml
v6/schemas/AssociationProperties.yaml
v6/schemas/OfferingProperties.yaml

#329 All enumerations to snake case. please pay attention to LevelOfQualification because I made the choice to explicitly indicate which levels are eqf and which is nlqf
#338 Suggestion from @hamrt to switch to an european standard and make it an array in course to support multiple modes of delivery.
#246 Added group types for all different types of offerings and an additionel default "group" type. Added an extra codetype "groupTypeCode" to support soft typed group types (which is widely used). in the otherCodes section of groups.
Point of attention for data model: There is not yet a way to indicate which groups (0..*) are related to an offering.

#329 #338 #246 Misc enumeration issues

---

.gitignore
ooapi_v6_i3.drawio
v6/enumerations/learningOutcomeLevel.yaml
v6/schemas/CourseProperties.yaml
v6/schemas/LearningComponent.yaml
v6/schemas/LearningOutcome.yaml
v6/schemas/ProgramProperties.yaml
v6/schemas/TestComponent.yaml
v6/spec.yaml

fixes #349,
#330 
#318 StudyLoad now is an array in course and program

Learning outcomes

---

CHANGELOG.md
v6/paths/LearningComponentOfferingAssociationInstance.yaml
v6/paths/TestComponentOfferingAssociationInstance.yaml
v6/schemas/OfferingProperties.yaml
v6/schemas/Pagination.yaml

Updated 2 bad examples and removed 2 required fields that were not specified.

409 correct some errors

---

CHANGELOG.md
v6/paths/CourseOfferingAssociationInstance.yaml
v6/paths/CourseOfferingAssociationInstanceExternalMe.yaml
v6/paths/CourseOfferingInstance.yaml
v6/paths/GroupInstance.yaml
v6/paths/LearningComponentOfferingAssociationInstance.yaml
v6/paths/LearningComponentOfferingInstance.yaml
v6/paths/PersonCollection.yaml
v6/paths/PersonGroupMemberships.yaml
v6/paths/PersonInstance.yaml
v6/paths/ProgrammeOfferingAssociationInstance.yaml
v6/paths/ProgrammeOfferingInstance.yaml
v6/paths/TestComponentOfferingAssociationAttemptInstance.yaml
v6/paths/TestComponentOfferingAssociationAttemptOnAssociationInstance.yaml
v6/paths/TestComponentOfferingAssociationInstance.yaml
v6/paths/TestComponentOfferingInstance.yaml

383 adding http statuscode 202 to responses
