- paths/BuildingCollection.yaml
- paths/CourseCollection.yaml
- paths/CourseGroupCollection.yaml
- paths/CourseResultCollection.yaml
- paths/EducationalDepartmentCollection.yaml
- paths/EducationalPlanCollection.yaml
- paths/FacultyCollection.yaml
- paths/NewsFeedCollection.yaml
- paths/NewsItemCollection.yaml
- paths/PersonCollection.yaml
- paths/RoomCollection.yaml
- paths/ScheduleCollection.yaml
- paths/TestResultCollection.yaml
The keys are in _embedded in the collection endpoints
This also prevents confusion between the key and the property: "items" in case of an array
> Replace the nondescriptive key: items with a descriptive key 

- v4/schemas/Program.yaml
"int" is not a valid OpenAPI data type. This was detected trying to load the spec with express-openapi-validator.
> Fix typo - "int" should be "integer"

- v4/paths/PersonMe.yaml
- v4/spec.yaml
Recently we concluded we need a /persons/me endpoint for the pilot Student mobility. Use case: the guest institution wants to fetch person information from the home institution, but only has a authentication token.
This PR is still a work in progress, but the general idea is:
- Add a new operation: GET /persons/me
- For this operation, an Authorization header is required
- Based on this header the implemented service should determine which person is authenticated, only these person details should be returned.
> Add persons me

- CHANGELOG.md
- v5/enumerations/postalType.yaml
This PR fixes #153 by adding `billing` as a new adress type to the PostalType enumeration list.
> Add billing addrestype

- CHANGELOG.md
- v5/enumerations/organizationType.yaml
This PR fixes #145:
It changes the enumeration for `organizationTypes`. Renamed `institution` to `institute` to prevent confusion with `root`. Added `branch`, `academy` and `school`.
> Change organization types

- CHANGELOG.md
- v5/schemas/Component.yaml
- v5/schemas/ComponentOffering.yaml
- v5/schemas/Course.yaml
- v5/schemas/CourseOffering.yaml
- v5/schemas/Offering.yaml
- v5/schemas/Program.yaml
- v5/schemas/ProgramOffering.yaml
Uitwerking van optie 2 in #164
Adresinformatie toegevoegd aan alle schema's met onderwijsaanbod:
- Offering
- Program
- ProgramOffering
- Component
- ComponentOffering
- Course
- CourseOffering
Gemaakte keuzes:
- Op alle plekken de array `addresses` toegevoegd omdat het aanbod verdeeld kan zijn over meerdere fysieke locaties
- Ieder array-item is een referentie naar het bestaande schema `Address.yaml`
- Niet verplicht
> Add `addresses` to all offerings 

- CHANGELOG.md
- v5/parameters/mainLanguage.yaml
- v5/parameters/teachingLanguage.yaml
- v5/paths/AcademicSessionOfferingCollection.yaml
- v5/paths/ComponentOfferingCollection.yaml
- v5/paths/CourseCollection.yaml
- v5/paths/CourseComponentCollection.yaml
- v5/paths/CourseOfferingCollection.yaml
- v5/paths/OrganizationComponentCollection.yaml
- v5/paths/OrganizationCourseCollection.yaml
- v5/paths/OrganizationOfferingCollection.yaml
- v5/paths/OrganizationProgramCollection.yaml
- v5/paths/ProgramCollection.yaml
- v5/paths/ProgramCourseCollection.yaml
- v5/paths/ProgramOfferingCollection.yaml
- v5/schemas/Component.yaml
- v5/schemas/Course.yaml
- v5/schemas/Offering.yaml
- v5/schemas/Program.yaml
This PR fixes #162 and also improves compatibility with RIO by moving the `mainLanguage` attribute from offerings to Programs, Courses and Offerings.
> Add `mainLanguage` to Programs, Courses and Programs and rename to `teachingLanguage`

- v5/paths/AcademicSessionCollection.yaml
- v5/paths/AcademicSessionOfferingCollection.yaml
- v5/paths/BuildingCollection.yaml
- v5/paths/BuildingRoomCollection.yaml
- v5/paths/ComponentOfferingCollection.yaml
- v5/paths/CourseCollection.yaml
- v5/paths/CourseComponentCollection.yaml
- v5/paths/CourseOfferingCollection.yaml
- v5/paths/NewsFeedCollection.yaml
- v5/paths/NewsFeedItemCollection.yaml
- v5/paths/OfferingAssociationCollection.yaml
- v5/paths/OrganizationCollection.yaml
- v5/paths/OrganizationComponentCollection.yaml
- v5/paths/OrganizationCourseCollection.yaml
- v5/paths/OrganizationOfferingCollection.yaml
- v5/paths/OrganizationProgramCollection.yaml
- v5/paths/PersonAssociationCollection.yaml
- v5/paths/PersonCollection.yaml
- v5/paths/ProgramCollection.yaml
- v5/paths/ProgramCourseCollection.yaml
- v5/paths/ProgramOfferingCollection.yaml
- v5/paths/RoomCollection.yaml
- v5/schemas/Pagination.yaml
This PR eliminates a lot of duplication by moving pagination details for collection responses to its own schema file.
@hamrt this PR changes nothing about how pagination works since @arthurvanalten PR's, but only restructures the files. Could you take a quick look to check If I've missed nothing?
> Makes Pagination more DRY by separating it out into its own schema file

- v5-beta/paths/OfferingGroupCollection.yaml
Minor fix to the group documentation to avoid the word "association"
> Clarify group docs

- v5-beta/enumerations/costType.yaml
- v5-beta/schemas/Cost.yaml
Deze PR maakt van `costType` een extensible enumeratie. De enumeratie is nu als volgt gespecificeerd:
```yaml
type: string
description: |
The type of the cost. This is an *extensible enumeration*.
The following values have been defined in the specification:
- `STAP eligible`: the costs that a student can get STAP subsidy for
- `total costs`: the total costs that a student is to pay to follow this offering
Implementations are allowed to add additional values to those above, as long as they do not overlap in definition to existing values.
example: total costs
x-ooapi-extensible-enum:
- STAP eligible
- total costs
```
En rendert als volgt:
Een belangrijke consequentie door de enumeratie op deze manier te specificeren is dat automatische validatie tools alle string waarden voor `costType` …
> Adds extensible enumeration for costType

- v5-beta/enumerations/codeType.yaml
- v5-beta/schemas/Building.yaml
- v5-beta/schemas/EducationSpecificationProperties.yaml
- v5-beta/schemas/IdentifierEntry.yaml
- v5-beta/schemas/PersonProperties.yaml
1. Vrij invulbare string voor `codeType` aangepast naar een extensible enum. Dit heeft impact op alle primaryCode en otherCode attributen
2. Aantal kleine aanpassingen in de `primaryCode` en `otherCodes` voorbeelden om het geheel consistenter te maken
3. In PersonProporties schema het attribuut `primaryCode` als readOnly gemarkeerd zodat deze niet verplicht is in POST /persons
> Improve identifier types

- docs/consumers/eduxchange.md
a new source object in the eduxchange consumer with attributes
- shortName
- primaryCode
- uuid
One question: the primaryCode is a string with the code and not an object with two strings 'codeType' and 'code'. It seems redundant to specify the codeType because it is the primary code. What could codeType be used for in primaryCode?
> add source object to eduxchange consumer

- v5-rc/spec.yaml
@hamrt deze PR op basis van een verzoek van Joost:
> Hi Jelmer, ik ben de nieuwste versie van de ooapi spec aan het testen en ik loop nog tegen wat dingen aan. De huidige validator in de gateway heeft moeite met het valideren van sommige responses (overflows etc) en geeft daar weinig feedback over, daarom heb ik ook nog getest met de de java validator die we ook gebruikt hebben voor demo-data. Die heeft een paar klachten over de spec die je nu krijgt met redocly bundle:
> 1 er zit een “components.schemas.allOf” property in de bundle; deze kan volgens mij gewoon weg maar geen idee waarom die er komt.
> 2. er zijn 2 tags met name “person_model” in de bundle; deze zijn gelijk en daar kan er dus ook een van weg. wederom geen idee waarom die er in zit.
Bij mij lijkt alles nog te werken na deze …
> Modify spec yaml

- v5-rc/schemas/CourseProperties.yaml
- v5-rc/schemas/ProgramProperties.yaml
The property admissionRequirements is an array of LanguageTypedString, and that should be reflected in the example, which was a string.
> Fixed example for admissionRequirements

- v5-rc/schemas/ProgramProperties.yaml
According to v5-rc/enumerations/codeType.yaml, the value CROHO is not allowed; probably the enum value crohoCreboCode was intended.
> Fixed codeType example value in ProgramProperties.

- v5/paths/AcademicSessionCollection.yaml
Fixes a bug: adds missing primaryCode query parameter to `GET /academic-sessions`.
> Fixes missing primaryCode query parameter

- v5/paths/EducationSpecificationCourseCollection.yaml
This PR fixes the following bug: missing q parameter in /education-specifications/{educationSpecificationId}/courses.
> Fix missing q parameter

- v5/paths/CourseOfferingCollection.yaml
This PR fixes a bug in `GET /courses/{courseId}/offerings`. This request currently specifies a filter on the attribute `modeOfStudy`. Since v5.0 offerings no longer have the `modeOfStudy` attribute.
This PR removes the filter option from this request.
> Fixes a bug with a filter in /courses/{courseId}/offerings

- v5/paths/ProgramCollection.yaml
The 'example' attribute was mistakenly named 'sort'.
> Fix typo in /programs `sort` param example.

- .github/workflows/release.yml
This PR adds a Github Action that creates a GH release whenever a tag `release-*` is pushed to the repository. Since the OOAPI repository contains multiple versions (v1 - v5), tags indicating a specific OOAPI version do not seem logical. That's why I've chosen the `release-*` pattern for tags.
When the action runs, it setups node and uses the `@redocly/cli` tool to generate a bundle file for v4 and v5 and attaches them to the release.
> Add release Gh action

- docs/technical/consumers/eduxchange.md
- docs/technical/profiles/eduxchange.md
ola, ik heb de docs van het eduxchange consumer object aangepast en het eduxchange profiel een kleine leesbaarheids update gegeven. Aan het profiel gaat later nog info toegevoegd worden, maar voor de developers is nu het consumer object van belang
> add consumer object for offering and update eduxchange profile

- v5/paths/AcademicSessionInstance.yaml
- v5/paths/AssociationInstance.yaml
- v5/paths/ComponentInstance.yaml
- v5/paths/CourseInstance.yaml
- v5/paths/EducationSpecificationInstance.yaml
- v5/paths/GroupInstance.yaml
- v5/paths/NewsItemInstance.yaml
- v5/paths/OfferingAssociationCollection.yaml
- v5/paths/OfferingInstance.yaml
- v5/paths/OrganizationInstance.yaml
- v5/paths/ProgramInstance.yaml
- v5/paths/RoomInstance.yaml
This PR makes sure all `sort` and `expand` query parameter serialization matches the description and documentation by adding `explode: false`.
> Add `explode: false` to all `sort` and `expand` query parameters

- v5/schemas/ComponentOffering.yaml
- v5/schemas/CourseOffering.yaml
- v5/schemas/OfferingProperties.yaml
- v5/schemas/ProgramOffering.yaml
This PR fixes two bug in the spec:
1. `modeOfStudy` is not an attribute in offerings (it used to be in v4), but it was required in ProgramOffering
2. ProgramOffering, CourseOffering and ProgramOffering all had a double reference to `academicSession`. This broke some validators. This PR removes one the references in each object.
> Fix bugs in the spec

- v5/schemas/CourseOffering.yaml
This PR removes the required attribute `modeOfStudy` from CourseOffering because this attribute is no longer an attribute in CourseOffering
> Remove required modeOfStudy from CourseOffering

- v6/enumerations/groupType.yaml
- v6/schemas/Country.yaml
- v6/schemas/CourseOffering.yaml
- v6/schemas/CourseProperties.yaml
- v6/schemas/LearningComponentOffering.yaml
- v6/schemas/ProgramOffering.yaml
- v6/schemas/TestComponentOffering.yaml
- v6/spec.yaml
This PR contains some minor grammar changes and other small fixes.
One change that I do want to mention is the change `enrollStartDate` and `enrollEndDate` to be date-times. In eduXchange we now have a consumer atrributes `enrollStartTime and `enrollEndTime` which we have to append to the dates which is really clunky. In practice, enrollment periods are specified with times, not just dates.
> Minor grammar, fixes and additions

- v6/schemas/CourseProperties.yaml
- v6/schemas/LearningComponent.yaml
- v6/schemas/OfferingProperties.yaml
- v6/schemas/ProgramProperties.yaml
- v6/schemas/TestComponent.yaml
This PR turns `teachingLanguage` into an array `teachingLanguages`. Rationale: this is a common request we get from institutions using the OOAPI. In The Netherlands, also DUO is changing "voertaal" to be an array.
> Turn teachingLanguage into an array

- v5/consumers/RIO/V1/examples/Offering.yaml
offering consumer rio modeOfDelivery example needs to be an array, not string.
> V5 specification: Fix rio offering modeOfDelivery example from string to array

- .github/workflows/check-changelog.yml
This PR adds a github action to verify that a PR updated the CHANGELOG.md file.
This check can be skipped by adding a label to the PR: `no changelog`
> Add a github action to check if a PR changed the CHANGELOG.md file

- CHANGELOG.md
- v6/paths/TestComponentOfferingAssociationAttemptCollection.yaml
- v6/paths/TestComponentOfferingAssociationAttemptInstance.yaml
Changed on summary path parameter and updated request/response on a get and put on attempt to schema TestComponentOfferingAssociationAttemptFull to include association attributes.
Where the request already included an association id the original schema was used.
> Optimalizations on attempts
